import type { ExamVariant } from "@/lib/types";

/**
 * ФАЙЛ СГЕНЕРИРОВАН. Не редактировать вручную — правки затрутся.
 * Пересобрать: npm run variants
 *
 * Фиксированные варианты по дисциплине «Алгоритмы и структуры данных».
 * Каждый вариант собран строго по плану спецификации: по каждой теме взято
 * столько заданий каждого уровня трудности, сколько положено (30 заданий).
 * Приоритет при отборе отдан заданиям, восстановленным из пробников ЦЕНТ.
 */
export const variants: ExamVariant[] = [
  {
    number: 1,
    questionIds: [
      "ct-ss-1",
      "ct-tr-5",
      "ct-ss-8",
      "ct-gr-3",
      "ct-ht-3",
      "ct-lb-4",
      "ct-lb-10",
      "ct-ls-6",
      "ct-fn-5",
      "ct-op-3",
      "ct-fn-3",
      "ct-op-2",
      "ct-ls-7",
      "ct-ht-2",
      "ct-ss-9",
      "ct-as-3",
      "ct-gr-8",
      "ct-ls-2",
      "ct-tr-2",
      "ct-cx-4",
      "ct-cx-1",
      "ct-fn-9",
      "ct-ht-4",
      "ct-as-8",
      "ct-lb-1",
      "ct-op-13",
      "ct-cx-2",
      "ct-as-2",
      "ct-gr-4",
      "ct-tr-7"
    ],
    fromMocks: 30
  },
  {
    number: 2,
    questionIds: [
      "ct-cx-1",
      "ct-ht-1",
      "ct-lb-6",
      "ct-tr-1",
      "ct-as-1",
      "ct-op-7",
      "ct-as-6",
      "ct-ss-6",
      "ct-ls-4",
      "ct-gr-3",
      "ct-cx-3",
      "ct-ls-7",
      "ct-ht-6",
      "ct-lb-9",
      "ct-ss-4",
      "ct-tr-9",
      "ct-fn-6",
      "ct-cx-5",
      "ct-ss-5",
      "ct-ls-5",
      "ct-fn-2",
      "ct-op-11",
      "ct-gr-6",
      "ct-op-14",
      "ct-gr-4",
      "ct-tr-10",
      "ct-ht-7",
      "ct-as-7",
      "ct-fn-9",
      "ct-lb-12"
    ],
    fromMocks: 30
  },
  {
    number: 3,
    questionIds: [
      "ct-fn-5",
      "ct-ss-3",
      "ct-tr-11",
      "ct-as-4",
      "ct-as-3",
      "ct-cx-1",
      "ct-fn-6",
      "ct-ls-3",
      "ct-op-5",
      "ct-tr-6",
      "ct-ht-1",
      "ct-ls-4",
      "ct-ss-4",
      "ct-gr-4",
      "ct-gr-3",
      "ct-cx-3",
      "ct-tr-10",
      "ct-cx-4",
      "ct-fn-1",
      "ct-ht-5",
      "ct-ss-8",
      "ct-as-5",
      "ct-ht-3",
      "ct-gr-7",
      "ct-lb-2",
      "ct-lb-5",
      "ct-ls-6",
      "ct-op-4",
      "ct-lb-3",
      "ct-op-16"
    ],
    fromMocks: 30
  },
  {
    number: 4,
    questionIds: [
      "ct-op-9",
      "ct-fn-9",
      "ct-as-1",
      "ct-ss-5",
      "ct-ss-9",
      "ct-op-12",
      "ct-cx-5",
      "ct-ht-5",
      "ct-lb-8",
      "ct-lb-7",
      "ct-fn-6",
      "ct-tr-9",
      "ct-ht-4",
      "ct-cx-2",
      "ct-gr-3",
      "ct-ls-1",
      "ct-as-7",
      "ct-op-15",
      "ct-gr-1",
      "ct-cx-1",
      "ct-tr-12",
      "ct-ls-4",
      "ct-ss-7",
      "ct-lb-13",
      "ct-gr-4",
      "ct-tr-5",
      "ct-fn-4",
      "ct-ls-6",
      "ct-ht-2",
      "ct-as-5"
    ],
    fromMocks: 30
  },
  {
    number: 5,
    questionIds: [
      "ct-gr-4",
      "ct-gr-2",
      "ct-tr-7",
      "ct-lb-11",
      "ct-cx-2",
      "ct-cx-1",
      "ct-tr-8",
      "ct-gr-3",
      "ct-ss-5",
      "ct-ls-7",
      "ct-ss-9",
      "ct-fn-6",
      "ct-fn-8",
      "ct-ht-7",
      "ct-fn-5",
      "ct-ht-6",
      "ct-op-8",
      "ct-as-8",
      "ct-lb-6",
      "ct-as-2",
      "ct-cx-4",
      "ct-ss-2",
      "ct-op-1",
      "ct-ls-5",
      "ct-ls-4",
      "ct-ht-4",
      "ct-op-6",
      "ct-as-4",
      "ct-lb-12",
      "ct-tr-11"
    ],
    fromMocks: 30
  }
];
